import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
  useAuthUser,
  withAuthUser,
  withAuthUserTokenSSR,
  AuthAction,
} from 'next-firebase-auth'
import FirebaseAuth from '../components/FirebaseAuth'

const Home = () => {
  const AuthUser = useAuthUser()
  console.log(AuthUser)
  const signOut = () => {
    AuthUser.signOut()
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome {AuthUser.firebaseUser ? AuthUser.displayName + '!' :  'to try-next-firebase-auth!'}
        </h1>
        <div>
          {AuthUser.firebaseUser &&
            <button type="button" onClick={() => {signOut()}}>Sign out</button>
          }
          {!AuthUser.firebaseUser &&
            <FirebaseAuth />
          }

        </div>

      </main>
    </div>
  )
}

export const getServerSideProps = withAuthUserTokenSSR()()

export default withAuthUser({
  whenUnauthedBeforeInit: AuthAction.RETURN_NULL,
  whenUnauthedAfterInit: AuthAction.RENDER
})(Home)
